### ISSUE TITLE
Performance issue or not?

### ISSUE THREAD

**Issue by alex-kovac** [seongjaelee/notational-velocity#22]
Hi! seongjaelee XL thanks for working on this package.

I would like to ask all of you how is notational-velocity package working for you? Especially how many notes are you having in the nv folder and how is your Atom performing.

I have a folder of about 2000 notes that used to be nvAlt notes folder and an issue with this package. When notational-velocity in Atom is summoned, Atom basically locks down for 10 minutes or more. After that, it becomes responsive... kind of... but as long as this package is activated, Atom will block/freeze when nv shortcut is activated. I am guessing nv is indexing the notes (?)

**Comment by seongjaelee** [comment]
Thanks for your e-mail.

Yes, unfortunately it loads all the notes in the directory every time you
start Atom.
This is inevitable since we need to search the contents.

If we want to improve the performance, we can do
1) Aynchronously read files so that you can still use Atom while reading
files, and/or
2) Cache the read information so that we don't have to scan it every time
we start Atom.

Unfortunately, I'm not working on the project for now, so you'd rather
implement it by yourself.

**Comment by jonmagic** [comment]
[I have a branch](https://github.com/seongjaelee/notational-velocity/compare/master...jonmagic:powered-by-docquery?expand=1) I was working on a couple of months ago that switches search to use [lunr.js](http://lunrjs.com/) via an npm package I built called [docquery](https://github.com/jonmagic/docquery).

I mention it because I was working towards a solution where the search index could be cached and reloaded from cache, rather than re-reading every file on the filesystem each time.

I'm not sure when I'll pick that up again, but it might be a viable solution for situations like this.

**Comment by alex-kovac** [comment]
Thanks for such quick replies!
- Caching sounds promising, given the user is not toying with the notes from elsewhere, I guess. Although, the files changed elsewhere could be detected. Original nv did it that way?
- Caching indicator would be convenient in both of the above approaches.

I am not sure if I will be able to do anything either, unfortunately. But who knows...

**Comment by seongjaelee** [comment]
#24 is now merged and in 0.2.0. Thanks Jonathan, and thanks Aleksandar.
