### ISSUE TITLE
Why remove instead of change name?

### ISSUE THREAD

**Issue by PixelT** [seongjaelee/notational-velocity#74]
This plugin was very useful...
Why you just don't change name of it? Without remove from atom packages....

**Comment by seongjaelee** [comment]
The main reason of removal was maintenance, not naming.

I thought this plugin was almost unusable because of so many deprecation warnings and bugs. We didn't have many people to maintain this package, and the evolution of Atom was too fast to follow up for me. I gave up fixing.

You still install/use this package manually via git.
If you could branch it and publish it to atom with your name, that would be even awesome.

I'm really happy the package was useful to you.
